<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-WebSocketTrading.Worker-47166564-ea53-429b-8b90-671a60c0c06d</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Binance.Net" Version="13.1.1" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.9" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\WebSocketTrading\WebSocketTrading.csproj" />
  </ItemGroup>
</Project>
