<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.1" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\BuildingBlocks\TradingPlatform.Kernel\TradingPlatform.Kernel.csproj" />
    <ProjectReference Include="..\MarketData.Domain\MarketData.Domain.csproj" />
  </ItemGroup>
</Project>
