<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\TradingAssistant.Application\TradingAssistant.Application.csproj" />
    <ProjectReference Include="..\TradingAssistant.Domain\TradingAssistant.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Binance.Net" Version="12.5.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.3">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.3" />
    <PackageReference Include="Microsoft.FASTER.Core" Version="2.6.5" />
    <PackageReference Include="X.Extensions.Logging.Telegram" Version="2.0.2" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
