// <auto-generated />
using System;
using CandlestickData.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CandlestickData.Infrastructure.Migrations
{
    [DbContext(typeof(CandlestickDataContext))]
    [Migration("20260224072915_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("CandlestickData.Domain.CandlestickRecord", b =>
                {
                    b.Property<string>("Symbol")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("TimeFrame")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OpenTime")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ClosePrice")
                        .HasPrecision(18, 8)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CloseTime")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("HighPrice")
                        .HasPrecision(18, 8)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("LowPrice")
                        .HasPrecision(18, 8)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("OpenPrice")
                        .HasPrecision(18, 8)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Volume")
                        .HasPrecision(18, 8)
                        .HasColumnType("TEXT");

                    b.HasKey("Symbol", "TimeFrame", "OpenTime");

                    b.HasIndex("Symbol", "TimeFrame", "OpenTime");

                    b.ToTable("Candlesticks");
                });

            modelBuilder.Entity("CandlestickData.Domain.SymbolIntegrity", b =>
                {
                    b.Property<string>("Symbol")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("TimeFrame")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DetectedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("GapFromOpenTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("GapToOpenTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastVerifiedOpenTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Symbol", "TimeFrame");

                    b.ToTable("SymbolIntegrities");
                });

            modelBuilder.Entity("CandlestickData.Domain.SyncCheckpoint", b =>
                {
                    b.Property<string>("Symbol")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("TimeFrame")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastSyncedOpenTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Symbol", "TimeFrame");

                    b.ToTable("SyncCheckpoints");
                });

            modelBuilder.Entity("CandlestickData.Domain.SyncJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StoppedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SyncJobs");
                });
#pragma warning restore 612, 618
        }
    }
}
