<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\MarketData.Application\MarketData.Application.csproj" />
    <ProjectReference Include="..\MarketData.Domain\MarketData.Domain.csproj" />
  </ItemGroup>
</Project>
